server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb01
    username: root
    password: dxq5522565
hikari:
maximum-pool-size: 20
minimum-idle: 10
mybatis:
    type-aliases-package: com.leyou.httpdemo.pojo
#yml的配置文件中，冒号后面必须跟一个空格
#数据库要提前建好，不然拿不到数据