server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb01
    username: root
    password: dxq5522565
  application:
    name: service-provider
hikari:
maximum-pool-size: 20
minimum-idle: 10
mybatis:
    type-aliases-package: cn.itcast.userservice.pojo

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找

#yml的配置文件中，冒号后面必须跟一个空格
#数据库要提前建好，不然拿不到数据
